workflows:
  ios-workflow:
    name: iOS Workflow 
    # ....
    environment:
      ios_signing:
        distribution_type: development # or: ad_hoc | development | enterprise
        bundle_identifier: com.uran.OlxClone
